function tests = test_sim_pipeline
tests = functiontests(localfunctions);
end

function testSimPipelineSmoke(testCase)
startup();

cfg = load_sim_config(struct( ...
    'output', struct('enableSave', false), ...
    'analysis', struct( ...
        'enablePointAnalysis', false, ...
        'recoveryEvaluation', struct('enable', false)), ...
    'degradation', struct('mode', 'none', 'enable', false), ...
    'scene', struct( ...
        'inheritRealTrack', false, ...
        'targetPositions', [0, 0, 0; 8, 6, 0], ...
        'targetAmplitudes', [1; 0.6], ...
        'targetPhasesDeg', [0; 20], ...
        'numAzimuthSamples', 48, ...
        'numRangeSamples', 96, ...
        'trackXLimits', [-50, 50], ...
        'trackYValue', -120, ...
        'trackZValue', 80), ...
    'radar', struct( ...
        'inheritRealRadar', false, ...
        'bandwidthHz', 2e8), ...
    'imaging', struct('grid', struct('numPixels', 64, 'xLimits', [-20, 20], 'yLimits', [-20, 20]), ...
                      'showProgress', false)));

result = run_sim_data_pipeline(cfg);

verifyEqual(testCase, size(result.image.image), [64, 64]);
verifyEqual(testCase, result.summary.targetCount, 2);
verifyEqual(testCase, result.degradation.totalMissing, 0);
verifyGreaterThan(testCase, result.image.peak.value, 0);
verifyEqual(testCase, result.source.meta.kind, 'sim');
verifyEqual(testCase, result.recoveryEvaluation.status, 'disabled');
verifyEqual(testCase, result.summary.recoveryEvaluationStatus, 'disabled');
verifyTrue(testCase, isfield(result, 'provenance'));
verifyEqual(testCase, result.provenance.pipeline.mode, 'sim');
verifyEqual(testCase, result.files.manifest, '');

provenance = build_pipeline_provenance(struct( ...
    'mode', 'sim', ...
    'config', cfg, ...
    'sourceData', result.source, ...
    'degradationInfo', result.degradation, ...
    'recoveryResult', result.recovery, ...
    'imageResult', result.image, ...
    'analysisResult', result.analysis, ...
    'recoveryEvaluation', result.recoveryEvaluation, ...
    'backend', result.backend, ...
    'runInfo', result.run));
verifyEqual(testCase, provenance.pipeline.mode, 'sim');
verifyEqual(testCase, provenance.source.kind, 'sim');
verifyEqual(testCase, provenance.source.echoSize, [96, 48]);
verifyEqual(testCase, provenance.recovery.status, 'skipped');
verifyEqual(testCase, provenance.imaging.grid.numPixels, 64);
end

function testSimPipelineWritesRunManifest(testCase)
startup();

tempProjectRoot = tempname;
mkdir(tempProjectRoot);
cleanup = onCleanup(@() rmdir(tempProjectRoot, 's')); %#ok<NASGU>

cfg = load_sim_config(struct( ...
    'path', struct('projectRoot', tempProjectRoot), ...
    'output', struct('enableSave', true), ...
    'debug', struct('showImageFigure', false, 'showPointTargetFigures', false), ...
    'analysis', struct( ...
        'enablePointAnalysis', false, ...
        'enableImageQuality', false, ...
        'recoveryEvaluation', struct('enable', false)), ...
    'degradation', struct('mode', 'none', 'enable', false), ...
    'scene', struct( ...
        'inheritRealTrack', false, ...
        'targetPositions', [0, 0, 0], ...
        'targetAmplitudes', 1, ...
        'targetPhasesDeg', 0, ...
        'numAzimuthSamples', 32, ...
        'numRangeSamples', 64, ...
        'trackXLimits', [-30, 30], ...
        'trackYValue', -100, ...
        'trackZValue', 70), ...
    'radar', struct( ...
        'inheritRealRadar', false, ...
        'bandwidthHz', 2e8), ...
    'imaging', struct( ...
        'grid', struct('numPixels', 32, 'xLimits', [-10, 10], 'yLimits', [-10, 10]), ...
        'showProgress', false)));

result = run_sim_data_pipeline(cfg);

verifyEqual(testCase, result.provenance.pipeline.mode, 'sim');
verifyTrue(testCase, exist(result.files.manifest, 'file') == 2);
verifyEqual(testCase, fullfile(result.run.runDir, 'run_manifest.txt'), result.files.manifest);
manifestText = fileread(result.files.manifest);
verifySubstring(testCase, manifestText, 'Run Manifest');
verifySubstring(testCase, manifestText, '[Pipeline]');
verifySubstring(testCase, manifestText, '- mode: sim');
end

function testSimPipelineWithRecovery(testCase)
startup();

cfg = load_sim_config(struct( ...
    'output', struct('enableSave', false), ...
    'analysis', struct( ...
        'enablePointAnalysis', true, ...
        'enableImageQuality', true, ...
        'recoveryEvaluation', struct( ...
            'enable', true, ...
            'outputs', struct( ...
                'saveMat', false, ...
                'saveSummary', false, ...
                'savePanel', false, ...
                'showPanel', false), ...
            'metricOptions', struct( ...
                'enablePointAnalysis', true, ...
                'enableImageQuality', true, ...
                'compareMode', 'amplitude')), ...
        'pointTarget', struct( ...
            'cutoutHeight', 16, ...
            'cutoutWidth', 16, ...
            'upsampleFactor', 8)), ...
    'degradation', struct( ...
        'enable', true, ...
        'mode', 'fixed_gap', ...
        'fixedGapRanges', [12, 18]), ...
    'recovery', struct( ...
        'enable', true, ...
        'method', 'cs_1d', ...
        'common', struct( ...
            'maxIter', 12, ...
            'verbose', false)), ...
    'scene', struct( ...
        'inheritRealTrack', false, ...
        'targetPositions', [0, 0, 0], ...
        'targetAmplitudes', 1, ...
        'targetPhasesDeg', 0, ...
        'numAzimuthSamples', 48, ...
        'numRangeSamples', 96, ...
        'trackXLimits', [-50, 50], ...
        'trackYValue', -120, ...
        'trackZValue', 80), ...
    'radar', struct( ...
        'inheritRealRadar', false, ...
        'bandwidthHz', 2e8), ...
    'imaging', struct('grid', struct('numPixels', 64, 'xLimits', [-20, 20], 'yLimits', [-20, 20]), ...
                      'showProgress', false)));

result = run_sim_data_pipeline(cfg);

verifyEqual(testCase, result.recovery.status, 'completed');
verifyEqual(testCase, result.summary.recoveryStatus, 'completed');
verifyEqual(testCase, size(result.image.image), [64, 64]);
verifyGreaterThan(testCase, result.recovery.recoveryInfo.iterations, 0);
verifyEqual(testCase, result.analysis.status, 'completed');
verifyEqual(testCase, result.analysis.pointTarget.status, 'completed');
verifyEqual(testCase, result.analysis.imageQuality.status, 'completed');
verifyGreaterThan(testCase, result.analysis.imageQuality.metrics.psnr, 0);
verifyEqual(testCase, result.recoveryEvaluation.status, 'completed');
verifyEqual(testCase, result.summary.recoveryEvaluationStatus, 'completed');
verifyTrue(testCase, isfield(result.recoveryEvaluation.cases, 'recovered_cs_1d'));
verifyTrue(testCase, isfield(result.recoveryEvaluation.cases, 'recovered_cs_2d'));
verifyTrue(testCase, isfield(result.recoveryEvaluation.comparisons, 'full_vs_recovered_cs_1d'));
verifyTrue(testCase, isfield(result.recoveryEvaluation.summary, 'bestMethodIfAny'));
end

function testBuildPlatformTrackArc(testCase)
track = build_platform_track(struct( ...
    'track', struct( ...
        'mode', 'arc', ...
        'numSamples', 32, ...
        'centerXY', [10, 20], ...
        'radius', 15, ...
        'angleLimitsDeg', [-30, 30], ...
        'zValue', 50)));

verifyEqual(testCase, numel(track.x), 32);
verifyEqual(testCase, numel(track.y), 32);
verifyEqual(testCase, numel(track.z), 32);
verifyEqual(testCase, track.z(1), 50);
end

function testBuildPlatformTrackBadRadius(testCase)
badScene = struct('track', struct( ...
    'mode', 'arc', ...
    'numSamples', 32, ...
    'centerXY', [10, 20], ...
    'radius', 0, ...
    'angleLimitsDeg', [-30, 30], ...
    'zValue', 50));

didThrow = false;
try
    build_platform_track(badScene);
catch errorInfo
    didThrow = true;
    verifySubstring(testCase, errorInfo.message, 'radius 必须大于 0');
end

verifyTrue(testCase, didThrow);
end

function testGeneratePointTargetDataFailsWhenRealInheritUnavailable(testCase)
startup();

tempProjectRoot = tempname;
mkdir(tempProjectRoot);
emptyRealDir = fullfile(tempProjectRoot, 'empty_real_data');
mkdir(emptyRealDir);
cleanup = onCleanup(@() rmdir(tempProjectRoot, 's')); %#ok<NASGU>

cfg = load_sim_config(struct( ...
    'path', struct('realDataRoot', emptyRealDir), ...
    'scene', struct('inheritRealTrack', true), ...
    'radar', struct('inheritRealRadar', true)));

didThrow = false;
try
    generate_point_target_data(cfg);
catch errorInfo
    didThrow = true;
    verifyEqual(testCase, errorInfo.identifier, 'generate_point_target_data:RealInheritFailed');
    verifySubstring(testCase, errorInfo.message, 'inheritRealTrack=false');
    verifySubstring(testCase, errorInfo.message, 'inheritRealRadar=false');
end

verifyTrue(testCase, didThrow);
end

function testFullImageReferenceCache(testCase)
startup();

tempProjectRoot = tempname;
mkdir(tempProjectRoot);
cleanup = onCleanup(@() rmdir(tempProjectRoot, 's')); %#ok<NASGU>

cfg = load_sim_config(struct( ...
    'path', struct('projectRoot', tempProjectRoot), ...
    'output', struct('enableSave', false), ...
    'cache', struct( ...
        'enableFullImageCache', true, ...
        'fullImageNamespace', 'baseline'), ...
    'scene', struct( ...
        'inheritRealTrack', false, ...
        'targetPositions', [0, 0, 0], ...
        'targetAmplitudes', 1, ...
        'targetPhasesDeg', 0, ...
        'numAzimuthSamples', 32, ...
        'numRangeSamples', 64, ...
        'trackXLimits', [-40, 40], ...
        'trackYValue', -80, ...
        'trackZValue', 60), ...
    'radar', struct( ...
        'inheritRealRadar', false, ...
        'bandwidthHz', 1.5e8), ...
    'imaging', struct( ...
        'grid', struct('numPixels', 48, 'xLimits', [-15, 15], 'yLimits', [-15, 15]), ...
        'showProgress', false)));

sourceData = generate_point_target_data(cfg);

[imageResult1, cacheInfo1] = get_full_image_reference(sourceData, cfg);
[imageResult2, cacheInfo2] = get_full_image_reference(sourceData, cfg);

verifyFalse(testCase, cacheInfo1.cacheHit);
verifyTrue(testCase, cacheInfo2.cacheHit);
verifyEqual(testCase, cacheInfo1.key, cacheInfo2.key);
verifyEqual(testCase, imageResult1.image, imageResult2.image);
verifyTrue(testCase, exist(cacheInfo2.folderPath, 'dir') == 7);
verifyTrue(testCase, exist(cacheInfo2.filePath, 'file') == 2);
verifyTrue(testCase, exist(cacheInfo2.infoFilePath, 'file') == 2);
verifyTrue(testCase, exist(cacheInfo2.infoFilePathCn, 'file') == 2);
verifySubstring(testCase, cacheInfo2.folderName, 'sim_baseline_');

infoText = fileread(cacheInfo2.infoFilePath);
verifyNotEmpty(testCase, infoText);
verifySubstring(testCase, infoText, 'Full Image Reference Cache');
verifySubstring(testCase, infoText, 'Folder Name: sim_baseline_');
verifySubstring(testCase, infoText, 'Source Name: sim_generate_point_target_data');
verifySubstring(testCase, infoText, 'imaging.grid.numPixels = 48');

infoTextCn = fileread(cacheInfo2.infoFilePathCn);
verifyNotEmpty(testCase, infoTextCn);
verifySubstring(testCase, infoTextCn, '缓存生成时间 (Timestamp)');
verifySubstring(testCase, infoTextCn, '缓存目录 (Folder): sim_baseline_');
verifySubstring(testCase, infoTextCn, '【雷达核心参数】');
verifySubstring(testCase, infoTextCn, '【成像网格参数】');
end

function testSaveRunManifest(testCase)
startup();

tempProjectRoot = tempname;
mkdir(tempProjectRoot);
cleanup = onCleanup(@() rmdir(tempProjectRoot, 's')); %#ok<NASGU>

cfg = load_sim_config(struct( ...
    'path', struct('projectRoot', tempProjectRoot), ...
    'output', struct('enableSave', true)));
runInfo = prepare_run_dir(cfg);

provenance = build_pipeline_provenance(struct( ...
    'mode', 'sim', ...
    'config', cfg, ...
    'runInfo', runInfo, ...
    'sourceData', struct( ...
        'track', struct('x', 1:3), ...
        'echo', zeros(4, 3), ...
        'mask', [true, false, true], ...
        'meta', struct('kind', 'sim', 'provider', 'unit')), ...
    'degradationInfo', struct('mode', 'fixed_gap', 'missingRatio', 1/3, 'totalMissing', 1), ...
    'recoveryResult', struct('status', 'skipped', 'method', 'cs_1d'), ...
    'imageResult', struct( ...
        'grid', struct('numPixels', 32, 'xLimits', [-5, 5], 'yLimits', [-5, 5]), ...
        'peak', struct('value', 10)), ...
    'analysisResult', struct('status', 'disabled'), ...
    'recoveryEvaluation', struct('enabled', false, 'status', 'disabled'), ...
    'backend', struct('name', 'cpu')));

result = struct('provenance', provenance);
filePath = save_run_manifest(result, runInfo, cfg);

verifyTrue(testCase, exist(filePath, 'file') == 2);
manifestText = fileread(filePath);
verifySubstring(testCase, manifestText, 'Run Manifest');
verifySubstring(testCase, manifestText, '[Source Data]');
verifySubstring(testCase, manifestText, '- kind: sim');
verifySubstring(testCase, manifestText, '[Degradation]');
verifySubstring(testCase, manifestText, '- mode: fixed_gap');

runInfo.enabled = false;
skippedPath = save_run_manifest(result, runInfo, cfg);
verifyEqual(testCase, skippedPath, '');
end
