function tests = test_sim_pipeline
tests = functiontests(localfunctions);
end

function testSimPipelineSmoke(testCase)
startup();

cfg = load_sim_config(struct( ...
    'output', struct('enableSave', false), ...
    'analysis', struct('enablePointAnalysis', false), ...
    'degradation', struct('mode', 'none', 'enable', false), ...
    'scene', struct( ...
        'inheritRealTrack', false, ...
        'targetPositions', [0, 0, 0; 8, 6, 0], ...
        'targetAmplitudes', [1; 0.6], ...
        'targetPhasesDeg', [0; 20], ...
        'numAzimuthSamples', 48, ...
        'numRangeSamples', 96, ...
        'trackXLimits', [-50, 50], ...
        'trackYValue', -120, ...
        'trackZValue', 80), ...
    'radar', struct( ...
        'inheritRealRadar', false, ...
        'bandwidthHz', 2e8), ...
    'imaging', struct('grid', struct('numPixels', 64, 'xLimits', [-20, 20], 'yLimits', [-20, 20]), ...
                      'showProgress', false)));

result = run_sim_data_pipeline(cfg);

verifyEqual(testCase, size(result.image.image), [64, 64]);
verifyEqual(testCase, result.summary.targetCount, 2);
verifyEqual(testCase, result.degradation.totalMissing, 0);
verifyGreaterThan(testCase, result.image.peak.value, 0);
verifyEqual(testCase, result.source.meta.kind, 'sim');
end

function testSimPipelineWithRecovery(testCase)
startup();

cfg = load_sim_config(struct( ...
    'output', struct('enableSave', false), ...
    'analysis', struct( ...
        'enablePointAnalysis', true, ...
        'enableImageQuality', true, ...
        'pointTarget', struct( ...
            'cutoutHeight', 16, ...
            'cutoutWidth', 16, ...
            'upsampleFactor', 8)), ...
    'degradation', struct( ...
        'enable', true, ...
        'mode', 'fixed_gap', ...
        'fixedGapRanges', [12, 18]), ...
    'recovery', struct( ...
        'enable', true, ...
        'method', '1d', ...
        'maxIter', 12, ...
        'verbose', false), ...
    'scene', struct( ...
        'inheritRealTrack', false, ...
        'targetPositions', [0, 0, 0], ...
        'targetAmplitudes', 1, ...
        'targetPhasesDeg', 0, ...
        'numAzimuthSamples', 48, ...
        'numRangeSamples', 96, ...
        'trackXLimits', [-50, 50], ...
        'trackYValue', -120, ...
        'trackZValue', 80), ...
    'radar', struct( ...
        'inheritRealRadar', false, ...
        'bandwidthHz', 2e8), ...
    'imaging', struct('grid', struct('numPixels', 64, 'xLimits', [-20, 20], 'yLimits', [-20, 20]), ...
                      'showProgress', false)));

result = run_sim_data_pipeline(cfg);

verifyEqual(testCase, result.recovery.status, 'completed');
verifyEqual(testCase, result.summary.recoveryStatus, 'completed');
verifyEqual(testCase, size(result.image.image), [64, 64]);
verifyGreaterThan(testCase, result.recovery.recoveryInfo.iterations, 0);
verifyEqual(testCase, result.analysis.status, 'completed');
verifyEqual(testCase, result.analysis.pointTarget.status, 'completed');
verifyEqual(testCase, result.analysis.imageQuality.status, 'completed');
verifyGreaterThan(testCase, result.analysis.imageQuality.metrics.psnr, 0);
end

function testBuildPlatformTrackArc(testCase)
track = build_platform_track(struct( ...
    'track', struct( ...
        'mode', 'arc', ...
        'numSamples', 32, ...
        'centerXY', [10, 20], ...
        'radius', 15, ...
        'angleLimitsDeg', [-30, 30], ...
        'zValue', 50)));

verifyEqual(testCase, numel(track.x), 32);
verifyEqual(testCase, numel(track.y), 32);
verifyEqual(testCase, numel(track.z), 32);
verifyEqual(testCase, track.z(1), 50);
end

function testBuildPlatformTrackBadRadius(testCase)
badScene = struct('track', struct( ...
    'mode', 'arc', ...
    'numSamples', 32, ...
    'centerXY', [10, 20], ...
    'radius', 0, ...
    'angleLimitsDeg', [-30, 30], ...
    'zValue', 50));

didThrow = false;
try
    build_platform_track(badScene);
catch errorInfo
    didThrow = true;
    verifySubstring(testCase, errorInfo.message, 'radius 必须大于 0');
end

verifyTrue(testCase, didThrow);
end

function testFullImageReferenceCache(testCase)
startup();

tempProjectRoot = tempname;
mkdir(tempProjectRoot);
cleanup = onCleanup(@() rmdir(tempProjectRoot, 's')); %#ok<NASGU>

cfg = load_sim_config(struct( ...
    'path', struct('projectRoot', tempProjectRoot), ...
    'output', struct('enableSave', false), ...
    'cache', struct( ...
        'enableFullImageCache', true, ...
        'fullImageNamespace', 'baseline'), ...
    'scene', struct( ...
        'inheritRealTrack', false, ...
        'targetPositions', [0, 0, 0], ...
        'targetAmplitudes', 1, ...
        'targetPhasesDeg', 0, ...
        'numAzimuthSamples', 32, ...
        'numRangeSamples', 64, ...
        'trackXLimits', [-40, 40], ...
        'trackYValue', -80, ...
        'trackZValue', 60), ...
    'radar', struct( ...
        'inheritRealRadar', false, ...
        'bandwidthHz', 1.5e8), ...
    'imaging', struct( ...
        'grid', struct('numPixels', 48, 'xLimits', [-15, 15], 'yLimits', [-15, 15]), ...
        'showProgress', false)));

sourceData = generate_point_target_data(cfg);

[imageResult1, cacheInfo1] = get_full_image_reference(sourceData, cfg);
[imageResult2, cacheInfo2] = get_full_image_reference(sourceData, cfg);

verifyFalse(testCase, cacheInfo1.cacheHit);
verifyTrue(testCase, cacheInfo2.cacheHit);
verifyEqual(testCase, cacheInfo1.key, cacheInfo2.key);
verifyEqual(testCase, imageResult1.image, imageResult2.image);
verifyTrue(testCase, exist(cacheInfo2.folderPath, 'dir') == 7);
verifyTrue(testCase, exist(cacheInfo2.filePath, 'file') == 2);
verifyTrue(testCase, exist(cacheInfo2.infoFilePath, 'file') == 2);
verifyTrue(testCase, exist(cacheInfo2.infoFilePathCn, 'file') == 2);
verifySubstring(testCase, cacheInfo2.folderName, 'sim_baseline_');

infoText = fileread(cacheInfo2.infoFilePath);
verifyNotEmpty(testCase, infoText);
verifySubstring(testCase, infoText, 'Full Image Reference Cache');
verifySubstring(testCase, infoText, 'Folder Name: sim_baseline_');
verifySubstring(testCase, infoText, 'Source Name: sim_generate_point_target_data');
verifySubstring(testCase, infoText, 'imaging.grid.numPixels = 48');

infoTextCn = fileread(cacheInfo2.infoFilePathCn);
verifyNotEmpty(testCase, infoTextCn);
verifySubstring(testCase, infoTextCn, '缓存生成时间 (Timestamp)');
verifySubstring(testCase, infoTextCn, '缓存目录 (Folder): sim_baseline_');
verifySubstring(testCase, infoTextCn, '【雷达核心参数】');
verifySubstring(testCase, infoTextCn, '【成像网格参数】');
end
