function tests = test_analysis_smoke
tests = functiontests(localfunctions);
end

function testEvaluateImageQualityAmplitude(testCase)
referenceImage = [1, 2; 3, 4];
targetImage = [1, 1; 3, 5];

metrics = evaluate_image_quality(referenceImage, targetImage);

verifyEqual(testCase, metrics.compareMode, 'amplitude');
verifyGreaterThan(testCase, metrics.mse, 0);
verifyGreaterThan(testCase, metrics.rmse, 0);
verifyGreaterThan(testCase, metrics.maxAbsError, 0);
verifyLessThan(testCase, metrics.normalizedCorrelation, 1);
end

function testPointTargetAnalysisSmoke(testCase)
startup();

cfg = load_sim_config(struct( ...
    'output', struct('enableSave', false), ...
    'analysis', struct( ...
        'enablePointAnalysis', true, ...
        'enableImageQuality', false, ...
        'pointTarget', struct( ...
            'cutoutHeight', 16, ...
            'cutoutWidth', 16, ...
            'upsampleFactor', 8, ...
            'enableTiltCorrection', true)), ...
    'degradation', struct('mode', 'none', 'enable', false), ...
    'scene', struct( ...
        'inheritRealTrack', false, ...
        'targetPositions', [0, 0, 0], ...
        'targetAmplitudes', 1, ...
        'targetPhasesDeg', 0, ...
        'numAzimuthSamples', 48, ...
        'numRangeSamples', 96, ...
        'trackXLimits', [-50, 50], ...
        'trackYValue', -120, ...
        'trackZValue', 80), ...
    'radar', struct( ...
        'inheritRealRadar', false, ...
        'bandwidthHz', 2e8), ...
    'imaging', struct('grid', struct('numPixels', 64, 'xLimits', [-20, 20], 'yLimits', [-20, 20]), ...
                      'showProgress', false)));

sourceData = generate_point_target_data(cfg);
imageResult = bp_imaging(sourceData, cfg);
analysisResult = point_target_analysis(imageResult, cfg);

verifyEqual(testCase, analysisResult.status, 'completed');
verifyEqual(testCase, analysisResult.pointTarget.status, 'completed');
verifyGreaterThan(testCase, analysisResult.pointTarget.xProfile.metrics.peakValue, 0);
verifyGreaterThan(testCase, analysisResult.pointTarget.yProfile.metrics.peakValue, 0);
verifyTrue(testCase, isfield(analysisResult.pointTarget.rotation, 'estimatedTiltDeg'));
end
