function tests = test_recovery_smoke
tests = functiontests(localfunctions);
end

function testBuildRecoveryProblem(testCase)
startup();

[sourceFull, sourceCut] = localBuildRecoveryCase();
problem = build_recovery_problem(sourceCut, sourceFull);

verifyEqual(testCase, size(problem.observedEcho), size(sourceCut.echo));
verifyEqual(testCase, problem.totalMissingSamples, size(sourceCut.echo, 1) * 6);
verifyTrue(testCase, problem.hasReference);
verifyEqual(testCase, problem.observedAzimuthMask(10:15), false(1, 6));
end

function testRunRecoveryCs1D(testCase)
startup();

[sourceFull, sourceCut] = localBuildRecoveryCase();
cfg = localRecoveryConfig('cs_1d');
result = run_recovery(sourceCut, cfg, sourceFull);

verifyEqual(testCase, result.status, 'completed');
verifyEqual(testCase, result.method, 'cs_1d');
verifyGreaterThan(testCase, result.recoveryInfo.iterations, 0);
verifyLessThanOrEqual(testCase, result.metrics.observedConsistencyErr, 1e-12);
verifyEqual(testCase, result.echo(:, sourceCut.mask), sourceCut.echo(:, sourceCut.mask), 'AbsTol', 1e-12);
end

function testRunRecoveryCs2D(testCase)
startup();

[sourceFull, sourceCut] = localBuildRecoveryCase();
cfg = localRecoveryConfig('cs_2d');
result = run_recovery(sourceCut, cfg, sourceFull);

verifyEqual(testCase, result.status, 'completed');
verifyEqual(testCase, result.method, 'cs_2d');
verifyGreaterThan(testCase, result.recoveryInfo.iterations, 0);
verifyLessThanOrEqual(testCase, result.metrics.observedConsistencyErr, 1e-12);
end

function [sourceFull, sourceCut] = localBuildRecoveryCase()
cfg = load_sim_config(struct( ...
    'output', struct('enableSave', false), ...
    'analysis', struct('enablePointAnalysis', false), ...
    'degradation', struct('mode', 'none', 'enable', false), ...
    'scene', struct( ...
        'inheritRealTrack', false, ...
        'targetPositions', [0, 0, 0], ...
        'targetAmplitudes', 1, ...
        'targetPhasesDeg', 0, ...
        'numAzimuthSamples', 32, ...
        'numRangeSamples', 64, ...
        'trackXLimits', [-40, 40], ...
        'trackYValue', -90, ...
        'trackZValue', 70), ...
    'radar', struct( ...
        'inheritRealRadar', false, ...
        'bandwidthHz', 1.2e8)));

sourceFull = generate_point_target_data(cfg);
sourceCut = sourceFull;
sourceCut.mask = true(1, size(sourceCut.echo, 2));
sourceCut.mask(10:15) = false;
sourceCut.echo(:, 10:15) = 0;
end

function cfg = localRecoveryConfig(methodName)
cfg = struct( ...
    'enable', true, ...
    'method', methodName, ...
    'common', struct( ...
        'maxIter', 15, ...
        'tol', 1e-4, ...
        'useFista', true, ...
        'normalizeInput', true, ...
        'verbose', false, ...
        'skipWhenNoMissing', true), ...
    'methods', struct( ...
        'cs_1d', struct('lambda', 0.02), ...
        'cs_2d', struct('lambda', 0.01)));
end
