function imageResult = bp_imaging(sourceData, config)
%BP_IMAGING BP 成像总入口。

pre = bp_precompute(sourceData, config);
[imageData, meta] = bp_backprojection(sourceData, pre, config);

imageAbs = abs(imageData);
[peakValue, peakIndex] = max(imageAbs(:));
[peakRow, peakCol] = ind2sub(size(imageAbs), peakIndex);

imageResult = struct();
imageResult.image = imageData;
imageResult.imageAbs = imageAbs;
imageResult.xAxis = pre.xAxis;
imageResult.yAxis = pre.yAxis;
imageResult.grid = struct( ...
    'xAxis', pre.xAxis, ...
    'yAxis', pre.yAxis, ...
    'xLimits', config.imaging.grid.xLimits, ...
    'yLimits', config.imaging.grid.yLimits, ...
    'numPixels', pre.imageSize);
imageResult.peak = struct( ...
    'value', peakValue, ...
    'row', peakRow, ...
    'col', peakCol, ...
    'x', pre.xAxis(peakRow), ...
    'y', pre.yAxis(peakCol));
imageResult.imaging = struct( ...
    'activeAzimuthCount', numel(pre.activeIndices), ...
    'totalAzimuthCount', size(sourceData.echo, 2), ...
    'rangeStep', sourceData.radar.rangeStep, ...
    'numRangeSamples', sourceData.radar.numRangeSamples, ...
    'numRangeSamplesUp', sourceData.radar.numRangeSamplesUp);
imageResult.meta = meta;
end

