function config = validate_real_config(config)
%VALIDATE_REAL_CONFIG 校验实测配置。
assert(isfield(config, 'path') && isfield(config.path, 'projectRoot'), ...
    '实测配置缺少 path.projectRoot。');
assert(isfield(config, 'source'), '实测配置缺少 source。');
assert(isfield(config.source, 'numFiles') && config.source.numFiles >= 1, ...
    'source.numFiles 必须大于等于 1。');
assert(isfield(config.source, 'filePattern') && ~isempty(config.source.filePattern), ...
    'source.filePattern 不能为空。');
assert(isfield(config.source, 'variableName') && ~isempty(config.source.variableName), ...
    'source.variableName 不能为空。');
assert(isfield(config.source, 'fieldMap') && isstruct(config.source.fieldMap), ...
    'source.fieldMap 必须是结构体。');

config = localValidateCommon(config);
end

function config = localValidateCommon(config)
assert(isfield(config, 'imaging') && isfield(config.imaging, 'grid'), ...
    '缺少 imaging.grid。');
assert(config.imaging.grid.numPixels >= 16, 'imaging.grid.numPixels 太小。');
assert(numel(config.imaging.grid.xLimits) == 2, 'xLimits 必须有两个元素。');
assert(numel(config.imaging.grid.yLimits) == 2, 'yLimits 必须有两个元素。');
assert(isfield(config, 'degradation'), '缺少 degradation。');
assert(isfield(config, 'recovery'), '缺少 recovery。');
assert(isfield(config, 'analysis'), '缺少 analysis。');
assert(isfield(config, 'cache'), '缺少 cache。');
assert(isfield(config, 'debug'), '缺少 debug。');
assert(isfield(config, 'output'), '缺少 output。');
assert(isfield(config, 'runtime'), '缺少 runtime。');
localValidateRecovery(config.recovery);
localValidateAnalysis(config.analysis);
localValidateCache(config.cache);
localValidateDebug(config.debug);
if ~isfield(config.path, 'cacheRoot') || isempty(config.path.cacheRoot)
    config.path.cacheRoot = 'cache';
end
end

function localValidateRecovery(recoveryConfig)
assert(isstruct(recoveryConfig) && isscalar(recoveryConfig), ...
    'recovery 必须是标量结构体。');
assert(isfield(recoveryConfig, 'enable') && islogical(recoveryConfig.enable) ...
    && isscalar(recoveryConfig.enable), ...
    'recovery.enable 必须是逻辑标量。');
assert(isfield(recoveryConfig, 'method') && ~isempty(recoveryConfig.method), ...
    'recovery.method 不能为空。');
methodName = lower(char(string(recoveryConfig.method)));
assert(any(strcmp(methodName, {'1d', '2d'})), ...
    'recovery.method 只支持 1d 或 2d。');
assert(isfield(recoveryConfig, 'lambda1D') && recoveryConfig.lambda1D >= 0, ...
    'recovery.lambda1D 必须大于等于 0。');
assert(isfield(recoveryConfig, 'lambda2D') && recoveryConfig.lambda2D >= 0, ...
    'recovery.lambda2D 必须大于等于 0。');
assert(isfield(recoveryConfig, 'maxIter') && recoveryConfig.maxIter >= 1 ...
    && recoveryConfig.maxIter == round(recoveryConfig.maxIter), ...
    'recovery.maxIter 必须是正整数。');
assert(isfield(recoveryConfig, 'tol') && recoveryConfig.tol > 0, ...
    'recovery.tol 必须大于 0。');
assert(isfield(recoveryConfig, 'useFista') && islogical(recoveryConfig.useFista) ...
    && isscalar(recoveryConfig.useFista), ...
    'recovery.useFista 必须是逻辑标量。');
assert(isfield(recoveryConfig, 'normalizeInput') ...
    && islogical(recoveryConfig.normalizeInput) ...
    && isscalar(recoveryConfig.normalizeInput), ...
    'recovery.normalizeInput 必须是逻辑标量。');
assert(isfield(recoveryConfig, 'verbose') && islogical(recoveryConfig.verbose) ...
    && isscalar(recoveryConfig.verbose), ...
    'recovery.verbose 必须是逻辑标量。');
assert(isfield(recoveryConfig, 'skipWhenNoMissing') ...
    && islogical(recoveryConfig.skipWhenNoMissing) ...
    && isscalar(recoveryConfig.skipWhenNoMissing), ...
    'recovery.skipWhenNoMissing 必须是逻辑标量。');
end

function localValidateAnalysis(analysisConfig)
assert(isstruct(analysisConfig) && isscalar(analysisConfig), ...
    'analysis 必须是标量结构体。');
assert(isfield(analysisConfig, 'enablePointAnalysis') ...
    && islogical(analysisConfig.enablePointAnalysis) ...
    && isscalar(analysisConfig.enablePointAnalysis), ...
    'analysis.enablePointAnalysis 必须是逻辑标量。');
assert(isfield(analysisConfig, 'enableImageQuality') ...
    && islogical(analysisConfig.enableImageQuality) ...
    && isscalar(analysisConfig.enableImageQuality), ...
    'analysis.enableImageQuality 必须是逻辑标量。');
assert(isfield(analysisConfig, 'pointTarget') && isstruct(analysisConfig.pointTarget), ...
    'analysis.pointTarget 必须是结构体。');
assert(isfield(analysisConfig, 'imageQuality') && isstruct(analysisConfig.imageQuality), ...
    'analysis.imageQuality 必须是结构体。');
assert(isfield(analysisConfig.pointTarget, 'cutoutHeight') ...
    && analysisConfig.pointTarget.cutoutHeight >= 8 ...
    && mod(analysisConfig.pointTarget.cutoutHeight, 2) == 0, ...
    'analysis.pointTarget.cutoutHeight 必须是不小于 8 的偶数。');
assert(isfield(analysisConfig.pointTarget, 'cutoutWidth') ...
    && analysisConfig.pointTarget.cutoutWidth >= 8 ...
    && mod(analysisConfig.pointTarget.cutoutWidth, 2) == 0, ...
    'analysis.pointTarget.cutoutWidth 必须是不小于 8 的偶数。');
assert(isfield(analysisConfig.pointTarget, 'upsampleFactor') ...
    && analysisConfig.pointTarget.upsampleFactor >= 1 ...
    && analysisConfig.pointTarget.upsampleFactor == round(analysisConfig.pointTarget.upsampleFactor), ...
    'analysis.pointTarget.upsampleFactor 必须是正整数。');
assert(isfield(analysisConfig.pointTarget, 'enableTiltCorrection') ...
    && islogical(analysisConfig.pointTarget.enableTiltCorrection) ...
    && isscalar(analysisConfig.pointTarget.enableTiltCorrection), ...
    'analysis.pointTarget.enableTiltCorrection 必须是逻辑标量。');
assert(isfield(analysisConfig.pointTarget, 'tiltThresholdDeg') ...
    && analysisConfig.pointTarget.tiltThresholdDeg >= 0, ...
    'analysis.pointTarget.tiltThresholdDeg 必须大于等于 0。');
assert(isfield(analysisConfig.pointTarget, 'tiltEdgeFraction') ...
    && analysisConfig.pointTarget.tiltEdgeFraction > 0 ...
    && analysisConfig.pointTarget.tiltEdgeFraction < 0.5, ...
    'analysis.pointTarget.tiltEdgeFraction 必须位于 (0, 0.5) 内。');
assert(isfield(analysisConfig.imageQuality, 'compareMode') ...
    && any(strcmpi(string(analysisConfig.imageQuality.compareMode), ["amplitude", "complex"])), ...
    'analysis.imageQuality.compareMode 只支持 amplitude 或 complex。');
end

function localValidateCache(cacheConfig)
assert(isstruct(cacheConfig) && isscalar(cacheConfig), ...
    'cache 必须是标量结构体。');
assert(isfield(cacheConfig, 'enableFullImageCache') ...
    && islogical(cacheConfig.enableFullImageCache) ...
    && isscalar(cacheConfig.enableFullImageCache), ...
    'cache.enableFullImageCache 必须是逻辑标量。');
assert(isfield(cacheConfig, 'fullImageNamespace') ...
    && ~isempty(cacheConfig.fullImageNamespace), ...
    'cache.fullImageNamespace 不能为空。');
end

function localValidateDebug(debugConfig)
assert(isstruct(debugConfig) && isscalar(debugConfig), ...
    'debug 必须是标量结构体。');
assert(isfield(debugConfig, 'showImageFigure') ...
    && islogical(debugConfig.showImageFigure) ...
    && isscalar(debugConfig.showImageFigure), ...
    'debug.showImageFigure 必须是逻辑标量。');
assert(isfield(debugConfig, 'showPointTargetFigures') ...
    && islogical(debugConfig.showPointTargetFigures) ...
    && isscalar(debugConfig.showPointTargetFigures), ...
    'debug.showPointTargetFigures 必须是逻辑标量。');
end
