function result = recover_cs_1d(problem, methodConfig, commonConfig)
%RECOVER_CS_1D 使用方位向 FFT 稀疏先验恢复缺失回波。
assert(isfield(methodConfig, 'lambda') && methodConfig.lambda >= 0, ...
    'cs_1d.lambda 必须大于等于 0。');

solverConfig = commonConfig;
solverConfig.lambda = methodConfig.lambda;

[echoRec, info] = run_fista_sparse_recovery( ...
    problem.observedEcho, ...
    problem.observedMatrixMask, ...
    solverConfig, ...
    @transform_azimuth_fft, ...
    @inverse_transform_azimuth_fft, ...
    'cs_1d');

result = struct();
result.echo = echoRec;
result.info = info;
end
