function result = recover_cs_2d(problem, methodConfig, commonConfig)
%RECOVER_CS_2D 使用二维 FFT 稀疏先验恢复缺失回波。
assert(isfield(methodConfig, 'lambda') && methodConfig.lambda >= 0, ...
    'cs_2d.lambda 必须大于等于 0。');

solverConfig = merge_structs(commonConfig, methodConfig);

[echoRec, info] = run_fista_sparse_recovery( ...
    problem.observedEcho, ...
    problem.observedMatrixMask, ...
    solverConfig, ...
    @transform_fft2d, ...
    @inverse_transform_fft2d, ...
    'cs_2d');

result = struct();
result.echo = echoRec;
result.info = info;
end
