function registry = get_recovery_registry()
%GET_RECOVERY_REGISTRY 恢复方法注册表。
registry = struct();
registry.cs_1d = struct( ...
    'family', 'cs', ...
    'description', '方位向 FFT 稀疏恢复', ...
    'handler', @recover_cs_1d);
registry.cs_2d = struct( ...
    'family', 'cs', ...
    'description', '二维 FFT 稀疏恢复', ...
    'handler', @recover_cs_2d);
end
