function recoveryConfig = prepare_recovery_config(recoveryConfig)
%PREPARE_RECOVERY_CONFIG 规范化并校验 recovery 配置。
assert(isstruct(recoveryConfig) && isscalar(recoveryConfig), ...
    'recovery 必须是标量结构体。');
assert(isfield(recoveryConfig, 'enable') && islogical(recoveryConfig.enable) ...
    && isscalar(recoveryConfig.enable), ...
    'recovery.enable 必须是逻辑标量。');
assert(isfield(recoveryConfig, 'method') && ~isempty(recoveryConfig.method), ...
    'recovery.method 不能为空。');
assert(isfield(recoveryConfig, 'common') && isstruct(recoveryConfig.common), ...
    'recovery.common 必须是结构体。');
assert(isfield(recoveryConfig, 'methods') && isstruct(recoveryConfig.methods), ...
    'recovery.methods 必须是结构体。');

methodName = lower(char(string(recoveryConfig.method)));
registry = get_recovery_registry();
supportedMethods = fieldnames(registry);
assert(any(strcmp(methodName, supportedMethods)), ...
    'recovery.method 不支持：%s。', methodName);

commonConfig = recoveryConfig.common;
assert(isfield(commonConfig, 'maxIter') && commonConfig.maxIter >= 1 ...
    && commonConfig.maxIter == round(commonConfig.maxIter), ...
    'recovery.common.maxIter 必须是正整数。');
assert(isfield(commonConfig, 'tol') && commonConfig.tol > 0, ...
    'recovery.common.tol 必须大于 0。');
assert(isfield(commonConfig, 'useFista') && islogical(commonConfig.useFista) ...
    && isscalar(commonConfig.useFista), ...
    'recovery.common.useFista 必须是逻辑标量。');
assert(isfield(commonConfig, 'normalizeInput') && islogical(commonConfig.normalizeInput) ...
    && isscalar(commonConfig.normalizeInput), ...
    'recovery.common.normalizeInput 必须是逻辑标量。');
assert(isfield(commonConfig, 'verbose') && islogical(commonConfig.verbose) ...
    && isscalar(commonConfig.verbose), ...
    'recovery.common.verbose 必须是逻辑标量。');
assert(isfield(commonConfig, 'skipWhenNoMissing') && islogical(commonConfig.skipWhenNoMissing) ...
    && isscalar(commonConfig.skipWhenNoMissing), ...
    'recovery.common.skipWhenNoMissing 必须是逻辑标量。');

methodConfig = get_method_config(recoveryConfig, methodName);
assert(isfield(methodConfig, 'lambda') && isnumeric(methodConfig.lambda) ...
    && isscalar(methodConfig.lambda) && methodConfig.lambda >= 0, ...
    'recovery.methods.%s.lambda 必须大于等于 0。', methodName);
if isfield(methodConfig, 'useFista')
    assert(islogical(methodConfig.useFista) && isscalar(methodConfig.useFista), ...
        'recovery.methods.%s.useFista 必须是逻辑标量。', methodName);
end

recoveryConfig.method = methodName;
recoveryConfig.common = commonConfig;
recoveryConfig.methods.(methodName) = methodConfig;
end
